name: Build and Deploy Website to Netlify

on:
  repository_dispatch:
    types:
      - build-and-deploy-web
      - start-build-and-deploy
  push:
    branches:
      - 'main'
    paths:
      - 'web/**'

env:
  SANITY_READ_TOKEN: ${{ secrets.SANITY_READ_TOKEN }}
  #SANITY_WRITE_TOKEN: ${{ secrets.SANITY_WRITE_TOKEN }} Should not be needed.
  TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v4
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
      - run: yarn --immutable
      - run: yarn workspace @dumppi/web build
        env:
          NODE_OPTIONS: '--max-old-space-size=8192'
      - name: Publish
        uses: Dumppiry/netlify-actions/cli@master
        with:
          args: deploy --dir=packages/web/public --filter @dumppi/web --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
