name: Build and Deploy to Netlify

on:
  push:
    branches:
      - "master"

env:
  SANITY_READ_TOKEN: ${{ secrets.SANITY_READ_TOKEN }}
  SANITY_WRITE_TOKEN: ${{ secrets.SANITY_WRITE_TOKEN }}

jobs:
  build:
    # 2. Using the latest Ubuntu image
    runs-on: ubuntu-latest

    steps:
      # Check out the current repository code
      - uses: actions/checkout@v1
      # 3. https://github.com/actions/setup-node#usage
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - run: cd web && npm install
      # This triggers `gatsby build` script in "package.json"
      - run: cd web && npm run build
      # 4. Deploy the gatsby build to Netlify
      - uses: netlify/actions/cli@master
        env:
          # NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          # NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: "188547f71bbdcb5649496bfb2c0871503913570f934224e7b89929c146ee3556"
          NETLIFY_SITE_ID: "0833e003-8187-4733-9187-48802d453c7b"
        with:
          # 5. "gatsby build" creates "public" folder, which is what we are deploying
          args: deploy --dir=web/public --prod
          # secrets: '["NETLIFY_AUTH_TOKEN", "NETLIFY_SITE_ID"]'
