name: Build and Deploy to Netlify

on:
  repository_dispatch:
    types:
      - start-build-and-deploy
  push:
    branches:
      - "master"

env:
  SANITY_READ_TOKEN: ${{ secrets.SANITY_READ_TOKEN }}
  SANITY_WRITE_TOKEN: ${{ secrets.SANITY_WRITE_TOKEN }}
  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
        working-directory: ./web
      - run: yarn build
        working-directory: ./web
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=web/public --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

  studio:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
        working-directory: ./studio
      - run: yarn build
        working-directory: ./studio
      - run: cp netlify.toml dist/netlify.toml
        working-directory: ./studio
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=studio/dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_STUDIO_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
